# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 00:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionTimePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DateTimeField()),
                ('consumption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimePointAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DateTimeField()),
                ('average', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
                ('tariff', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='consumptiontimepoint',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.UserData'),
        ),
    ]
